apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-web-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-web
  minReplicas: 2 # Minimum number of replicas to maintain
  maxReplicas: 10 # Maximum number of replicas to scale up to
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50 ## Target CPU utilization percentage
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 60 ## Target Memory utilization percentage
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 180  # Wait for 3 minutes before scaling out
      selectPolicy: Min # Choose the  policy for scaling in  that has the minimum value.
      policies:
        - type: Percent
          value: 100       # Can scale up by 100% of pods thats currently running
          periodSeconds: 30
        - type: Pods
          value: 5      
          periodSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 180  # Wait 3 min before scaling in
      selectPolicy: Max 
      policies:
        - type: Percent
          value: 50     # Can scale down by 50% of pods each time but it will not scale down to 0 pods to maintain the minimum number of pods.
          periodSeconds: 30 
