apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-web-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-web
  minReplicas: 2 # Minimum number of replicas to maintain
  maxReplicas: 10 # Maximum number of replicas to scale up to
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50 ## Target CPU utilization percentage
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 60 ## Target Memory utilization percentage
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60  # Wait for 5 minutes before scaling up
      selectPolicy: Min # Choose the  policy for scaling up that has the minimum value. It can create more pods if the load is continuosly high.
      policies:
        - type: Percent
          value: 100       # Can scale up by 100% of pods
          periodSeconds: 10
        - type: Pods
          value: 5      
          periodSeconds: 10
    scaleDown:
      stabilizationWindowSeconds: 300  # Wait 5 min before scaling down
      selectPolicy: Max # Choose the maximum policy for scaling down
      policies:
        - type: Percent
          value: 100     # Can scale down by 100% of pods but it will not scale down to 0 pods to maintain the minimum number of pods.
          periodSeconds: 10 
